spring:
  application:
    name: product-service

  data:
    mongodb:
      database: ecommerce
      uri: mongodb+srv://diallodev:softwaredeveloper@ecommerce.brcmh1o.mongodb.net/ecommerce?retryWrites=true&w=majority
